version: '3.1'

services:

  db:
    image: postgres
    container_name: java_ee_lesson
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: books

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: adminer_java_ee
    restart: always
    ports:
      - 8080:8080